#!/bin/bash
sudo apt update
sudo apt full-upgrade -y
sudo apt-get install --assume-yes \
     apt-transport-https \
     autoconf \
     automake \
     bsd-mailx \
     build-essential \
     ca-certificates \
     ccache \
     chromium-browser  \
     clang \
     curl \
     dbus-x11 \
     debhelper \
     dpkg-dev \
     fonts-firacode \
     gawk \
     gcc \
     gfortran \
     gnupg \
     gnupg-agent \
     gnutls-bin \
     gnutls-dev \
     gvfs \
     heif-gdk-pixbuf \
     ibus-gtk3 \
     imagemagick \
     libacl1-dev \
     libaspell15 \
     libasyncns0 \
     libatk-bridge2.0-0t64 \
     libatk1.0-0t64 \
     libatspi2.0-0t64 \
     libblas-dev \
     libbrotli1 \
     libc6 \
     libc6-dev \
     libcairo-gobject2 \
     libcairo2 \
     libcanberra-gtk3-0t64 \
     libcanberra-gtk3-module \
     libcanberra0t64 \
     libclang-dev \
     libconfig-dev \
     libdatrie1 \
     libdb5.3t64 \
     libdbus-1-dev \
     libdrm2 \
     libegl1 \
     libepoxy0 \
     libfontconfig1 \
     libfreetype6 \
     libgbm1 \
     libgcc-s1 \
     libgccjit-13-dev \
     libgdk-pixbuf2.0-0 \
     libgif-dev \
     libgif7 \
     libgl1 \
     libglvnd0 \
     libglx0 \
     libgpm-dev \
     libgpm2 \
     libgraphite2-3 \
     libgstreamer-gl1.0-0 \
     libgstreamer-plugins-base1.0-0 \
     libgstreamer1.0-0 \
     libgtk-3-0 \
     libgtk-3-dev \
     libgudev-1.0-0 \
     libharfbuzz-dev \
     libharfbuzz-icu0 \
     libharfbuzz0b \
     libhyphen0 \
     libibus-1.0-5 \
     libice6 \
     libindicator7 \
     libjansson-dev\
     libjansson4 \
     libjbig0 \
     libjpeg-dev \
     libjpeg-turbo8 \
     liblapack-dev \
     liblcms2-2 \
     liblcms2-dev \
     liblockfile-dev \
     liblockfile1 \
     libltdl7 \
     libm17n-0 \
     libm17n-dev \
     libmagickwand-dev \
     libmpc3 \
     libmpfr6 \
     libncurses5-dev \
     libnotify4 \
     libnss-mdns \
     libnss-myhostname \
     libnss-systemd \
     libogg0 \
     liborc-0.4-0 \
     liboss4-salsa2 \
     libotf-dev \
     libpango-1.0-0 \
     libpangocairo-1.0-0 \
     libpangoft2-1.0-0 \
     libpixman-1-0 \
     libpng-dev \
     libpng16-16 \
     libpulse0 \
     librsvg2-2 \
     librsvg2-dev \
     librsvg2-dev \
     libsasl2-2 \
     libsecret-1-0 \
     libselinux1-dev \
     libsm6 \
     libsndfile1 \
     libsoup2.4-1 \
     libstdc++6 \
     libsystemd-dev \
     libtdb1 \
     libthai0 \
     libtiff-dev \
     libtree-sitter-dev \
     libvorbis0a \
     libvorbisenc2 \
     libvorbisfile3 \
     libwebpdemux2 \
     libwoff1 \
     libx11-6 \
     libx11-dev \
     libx11-xcb1 \
     libxau6 \
     libxcb-cursor0 \
     libxcb-render0 \
     libxcb-shm0 \
     libxcb1 \
     libxcomposite1 \
     libxcursor1 \
     libxdamage1 \
     libxdmcp6 \
     libxext6 \
     libxfixes3 \
     libxft-dev \
     libxi6 \
     libxinerama1 \
     libxkbcommon0 \
     libxml2 \
     libxml2-dev \
     libxpm-dev \
     libxpm4 \
     libxrandr2 \
     libxrender1 \
     libxslt1.1 \
     libxss1 \
     libxt-dev \
     libyajl2 \
     make \
     pandoc \
     procps \
     quilt \
     sharutils \
     software-properties-common \
     sqlite3 \
     texinfo \
     texlive-latex-base \
     valgrind \
     w3m \
     wget \
     xaw3dg-dev \
     zlib1g-dev


wget https://mirrors.ibiblio.org/gnu/emacs/emacs-30.1.tar.xz
tar -xvf emacs-30.1.tar.xz
cd emacs-30.1

./autogen.sh
./configure --without-compress-install --with-native-compilation  --with-mailutils
make
sudo make install
